name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'pages'
          destination-github-username: 'tuxsisir'
          destination-repository-name: 'test-pull'
          user-email: samratsisir294@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
          target-directory: 'pages/dashboard'
      - name: Test changes move from test-push to test-pull
        run: echo $DESTINATION_CLONED_DIRECTORY
