name: CI

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push pages
        id: push_pages
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          DESTINATION_REPO_NAME: ${{ secrets.DESTINATION_REPO_NAME }}
        with:
          source-directory: 'pages'
          destination-github-username: '${{ secrets.GH_USERNAME }}'
          destination-repository-name: '${{ secrets.DESTINATION_REPO_NAME }}'
          user-email: ${{ secrets.USER_EMAIL }}
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: dev
          target-directory: 'pages/dashboard'
      - name: Push assets
        id: push_assets
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          DESTINATION_REPO_NAME: ${{ secrets.DESTINATION_REPO_NAME }}
        with:
          source-directory: 'assets'
          destination-github-username: '${{ secrets.GH_USERNAME }}'
          destination-repository-name: '${{ secrets.DESTINATION_REPO_NAME }}'
          user-email: ${{ secrets.USER_EMAIL }}
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: dev
          target-directory: 'assets/'
      - name: Test changes move from test-push to test-pull
        run: echo $DESTINATION_CLONED_DIRECTORY
